export const BEGIN_SIGNUP_PROCESS = 'BEGIN_SIGNUP_PROCESS';
export const SIGNUP_PROCESS_SUCCESS = 'SIGNUP_PROCESS_SUCCESS';
export const SIGNUP_PROCESS_ERROR = 'SIGNUP_PROCESS_ERROR';
export const RESET_SIGNUP_PROCESS = 'RESET_SIGNUP_PROCESS';
export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';
export const LOGIN_PROCESS_ERROR = 'LOGIN_PROCESS_ERROR';
export const LOGIN_PROCESS_BEGIN = 'LOGIN_PROCESS_BEGIN';
export const SET_USERNAME = 'SET_USERNAME';
export const BEGIN_LOADING_MESSAGES = 'BEGIN_LOADING_MESSAGES';
export const SUCCESS_LOADING_MESSAGES = 'SUCCESS_LOADING_MESSAGES';
export const ERROR_LOADING_MESSAGES = 'ERROR_LOADING_MESSAGES';

export const EDIT_MESSAGES = 'EDIT_MESSAGES';